FROM clarkwu/polyaxon-core

MAINTAINER mourad mourafiq <mourad@polyaxon.com>

ENV POLYAXON_SERVICE=dockerizer

WORKDIR /polyaxon
COPY . /polyaxon

RUN pip3 install --no-cache-dir -r /requirements/dockerizer/requirements-dev.txt

ENTRYPOINT ["python3", "polyaxon/manage.py",  "build"]
