sudo: required

services:
  - docker

language:
  - bash

env:
  - VERSION="2"
  - VERSION="3"

script:
  - ./build.sh $VERSION

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    ./push.sh $VERSION;
    fi
