sudo: required

services:
  - docker

language:
  - bash

script:
  - chmod +x ./polyaxon/*
  - ./polyaxon/build-services.sh "$TRAVIS_BRANCH" "$TRAVIS_BRANCH"

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - ./polyaxon/push-services.sh "$TRAVIS_BRANCH"

notifications:
  email: false